# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  nixpkgs.hostPlatform = "x86_64-linux";

  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e42584b0-c9f7-46de-8e85-00b902c2d497";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-722cea2b-4a1f-4c51-84f5-3090b69327ad".device = "/dev/disk/by-uuid/722cea2b-4a1f-4c51-84f5-3090b69327ad";
  # Enable swap on luks
  boot.initrd.luks.devices."luks-335510bd-4e31-443b-a111-585046c88f80".device = "/dev/disk/by-uuid/335510bd-4e31-443b-a111-585046c88f80";
  boot.initrd.luks.devices."luks-335510bd-4e31-443b-a111-585046c88f80".keyFile = "/crypto_keyfile.bin";

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/23F1-F4C8";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/307b324a-fec9-45fa-8e0b-0fccc01ca3d6"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
