# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  environment.persistence."/nix/persist" = {
    hideMounts = true;
    allowTrash = true;
    directories = [
      "/etc/nixos"
      "/etc/ssh"
      "/etc/NetworkManager"
      "/var/lib/iwd"
      "/var/lib/bluetooth"
      "/var/lib/systemd/backlight"
      "/var/lib/nixos"
    ];
    files = [
      # `machine-id` é utilizado pelo systemd para o journal
      "/etc/machine-id"
    ];
  };

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "noatime" "mode=0755" "size=2G" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/94A4-5171";
      fsType = "vfat";
      options = [ "defaults" "umask=0077" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/76cc8549-1fe9-4b93-85c6-8e1a23fe828e";
      neededForBoot = true;
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/76cc8549-1fe9-4b93-85c6-8e1a23fe828e";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=@var_log" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/disk/by-uuid/76cc8549-1fe9-4b93-85c6-8e1a23fe828e";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=@libvirt" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/76cc8549-1fe9-4b93-85c6-8e1a23fe828e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e12d68a1-2846-43f5-87f8-6d6dda6a4781"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
