;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-beginning-of-statement
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comint-delchar-or-maybe-eof
        electric-pair-delete-pair
        end-of-buffer
        haskell-indentation-common-electric-command
        haskell-indentation-newline-and-indent
        ignore
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        lsp-ui-doc--handle-mouse-movement
        org-self-insert-command
        overwrite-mode
        prolog-inferior-self-insert-command
        ryanmarcus/backward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        comint-send-input
        compile
        eval-last-sexp
        goto-line
        handle-switch-frame
        lsp-signature-stop
        mouse-drag-bottom-edge
        switch-to-buffer
        ))
